### ISSUE TITLE
Too many pull requests in the done column

### ISSUE THREAD

**Issue by simoneb** [nearform/unbreakci#152]
When using this app we're getting lots of pull requests in the done column of the board. This is not really expected because it doesn't look like CI ever failed for those pull requests.

I wonder if PRs are being added to the board in circumstances other than CI failing for them.

**Comment by brunopascottini** [comment]
Information related to issues that did not fail and were added to the bench board will be available in [this spreadsheet](https://docs.google.com/spreadsheets/d/1jd6mtvvVttuuNCFJOus4NTmU1BW3aR9A8v5AEoSB5C4/edit?usp=sharing) as investigation progresses

**Comment by simoneb** [comment]
post your findings here please
